# -*- coding: utf-8 -*-
"""hackernews.ipy

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17HxPefBgl6kD5VSw2rEHuftxCLFq_COI
"""

#scrap the news from 
from pygooglenews import GoogleNews
import pandas as pd
df=pd.DataFrame({})
l1=[]
l2=[]
l3=[]
gn=GoogleNews()
s=gn.search('hacker news')
entries=s['entries']
for detail in entries:
  a=detail["link"]
  l1.append(a)
for detail in entries:
  b=detail["title"]
  l2.append(b)
for detail in entries:
  c=detail["published"]
  l3.append(c)

#convert the data into frame
df=pd.DataFrame({'link':l1,'title':l2,'published':l3})
display(df)
df_data=df[['title']]
df_data.head()

#perform text pre-processing and visualize using bar plot and word could
import matplotlib.pyplot as plt
from wordcloud import WordCloud,STOPWORDS
wordcloud=WordCloud(background_color="pink",width=1600,height=1000).generate(' '.join(df_data['title'].tolist()))
plt.figure( figsize=(12,10), facecolor='k')
plt.imshow(wordcloud)